# Generated by Django 5.2.8 on 2025-11-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('education_level', models.CharField(blank=True, choices=[('High School', 'High School'), ('Undergraduate', 'Undergraduate'), ('Graduate', 'Graduate')], max_length=50, null=True)),
                ('experience_level', models.CharField(blank=True, choices=[('Fresher', 'Fresher'), ('Junior', 'Junior'), ('Mid', 'Mid')], max_length=20, null=True)),
                ('preferred_career_track', models.CharField(blank=True, choices=[('Web Development', 'Web Development'), ('Data', 'Data'), ('Design', 'Design'), ('Marketing', 'Marketing')], max_length=50, null=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('bio', models.TextField(blank=True, null=True)),
                ('cv_text', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
