# Generated by Django 5.2.8 on 2025-11-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_email_otp_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cv_text',
        ),
        migrations.AddField(
            model_name='user',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
