# Generated by Django 5.2.8 on 2025-11-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('required_skills', models.JSONField(default=list)),
                ('experience_level', models.CharField(choices=[('Fresher', 'Fresher'), ('Junior', 'Junior'), ('Mid', 'Mid')], max_length=20)),
                ('job_type', models.CharField(choices=[('Internship', 'Internship'), ('Part-time', 'Part-time'), ('Full-time', 'Full-time'), ('Freelance', 'Freelance')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
