# Generated by Django 5.2.8 on 2025-11-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
