# Generated by Django 5.2.8 on 2025-11-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningresource',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
