# Generated by Django 5.2.8 on 2025-11-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_learningresource_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningresource',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
